<?php

namespace LLAR\Core\MfaFlow\Providers\Email;

use LLAR\Core\MfaFlow\MfaApiClient;
use LLAR\Core\MfaFlow\Providers\MfaProviderInterface;
use LLAR\Core\MfaFlow\MfaRestApi;
use LLAR\Core\Helpers;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Email MFA provider: handshake and verify via API (LLA_MFA_API_BASE_URL + LLA_MFA_API_PATH).
 * Builds send_email_url and send_email_url_fallback from send_email_secret for the handshake payload.
 * External app redirects user here; app calls site send_email_url to deliver OTP.
 */
class LlarMfaProvider implements MfaProviderInterface {

	const PROVIDER_ID = 'llar';
	const AJAX_ACTION = 'llar_mfa_flow_send_code';

	/**
	 * @return string
	 */
	public function get_id() {
		return self::PROVIDER_ID;
	}

	/**
	 * @return string
	 */
	public function get_label() {
		return __( 'External app (LLAR MFA API)', 'limit-login-attempts-reloaded' );
	}

	/**
	 * Build send_email_url (REST) and send_email_url_fallback (AJAX) for handshake API.
	 * No secret in URL; caller must send secret in POST body. send_email_secret stays in payload for the API to use.
	 *
	 * @param string|null $send_email_secret Unused (kept for interface); secret is passed in handshake payload for POST body.
	 * @return array { send_email_url: string, send_email_url_fallback: string }
	 */
	public function build_send_email_urls( $send_email_secret = null ) {
		$send_email_url          = MfaRestApi::get_send_code_rest_url();
		$send_email_url_fallback = add_query_arg(
			array(
				'action'      => self::AJAX_ACTION,
				'_ajax_nonce' => wp_create_nonce( self::AJAX_ACTION ),
			),
			admin_url( 'admin-ajax.php' )
		);
		return array(
			'send_email_url'          => $send_email_url,
			'send_email_url_fallback' => $send_email_url_fallback,
		);
	}

	/**
	 * @param array $payload user_ip, login_url, user_group, is_pre_authenticated.
	 * Secret is generated by MFA app and returned in response; plugin sends only send_email_url(s).
	 * @return array { success: bool, data: array|null, error: string|null }
	 */
	public function handshake( array $payload ) {
		$urls    = $this->build_send_email_urls();
		$payload = array_merge( $payload, $urls );
		$opts    = $this->get_request_options();
		$api     = new MfaApiClient();
		return $api->handshake( $payload, $opts );
	}

	/**
	 * @param string $token  Session token.
	 * @param string $secret Session secret.
	 * @return array { success: bool, data: array|null, error: string|null }
	 */
	public function verify( $token, $secret ) {
		$opts = $this->get_request_options();
		$api  = new MfaApiClient();
		return $api->verify( $token, $secret, $opts );
	}

	/**
	 * Send verification code to the user by email.
	 *
	 * @param \WP_User $user User to send code to.
	 * @param string  $code Verification code.
	 * @return array { success: bool, message: string|null }
	 */
	public function send_code( $user, $code ) {
		if ( ! $user || ! is_a( $user, 'WP_User' ) || empty( $user->user_email ) ) {
			return array(
				'success' => true,
				'message' => null,
			);
		}

		$subject = __( 'Verify your login', 'limit-login-attempts-reloaded' );

		$site_url    = home_url();
		$site_domain = str_replace( array( 'http://', 'https://' ), '', $site_url );

		$ips        = Helpers::get_all_ips();
		$ip_address = '';
		if ( isset( $ips['HTTP_X_FORWARDED_FOR'] ) && is_string( $ips['HTTP_X_FORWARDED_FOR'] ) && $ips['HTTP_X_FORWARDED_FOR'] !== '' ) {
			$ip_address = $ips['HTTP_X_FORWARDED_FOR'];
		} elseif ( isset( $ips['REMOTE_ADDR'] ) && is_string( $ips['REMOTE_ADDR'] ) && $ips['REMOTE_ADDR'] !== '' ) {
			$ip_address = $ips['REMOTE_ADDR'];
		}

		$browser_label = isset( $_SERVER['HTTP_USER_AGENT'] ) && is_string( $_SERVER['HTTP_USER_AGENT'] ) ? $_SERVER['HTTP_USER_AGENT'] : '';

		$timestamp   = current_time( 'timestamp' );
		$date_format = get_option( 'date_format' );
		$time_format = get_option( 'time_format' );
		$format      = is_string( $date_format ) && is_string( $time_format ) && $date_format !== '' && $time_format !== ''
			? $date_format . ' ' . $time_format
			: 'F j, Y \a\t g:i A';
		$time_label  = date_i18n( $format, $timestamp );

		$ttl_seconds = defined( 'LLA_MFA_FLOW_OTP_TTL' ) ? (int) LLA_MFA_FLOW_OTP_TTL : 180;
		$ttl_seconds = $ttl_seconds > 0 ? $ttl_seconds : 180;
		$code_ttl    = (int) max( 1, ceil( $ttl_seconds / 60 ) );

		$code_safe         = (string) $code;
		$site_domain_safe  = (string) $site_domain;
		$ip_safe           = (string) $ip_address;
		$browser_safe      = (string) $browser_label;
		$time_safe         = (string) $time_label;
		$code_ttl_minutes  = $code_ttl;

		ob_start();
		include LLA_PLUGIN_DIR . 'views/emails/mfa-verification.php';
		$body = (string) ob_get_clean();

		$headers  = array( 'Content-Type: text/html; charset=UTF-8' );
		$to_email = $user->user_email;
		$sent     = wp_mail( $to_email, $subject, $body, $headers );
		if ( $sent ) {
			return array(
				'success' => true,
				'message' => null,
			);
		}
		return array(
			'success' => false,
			'message' => 'Failed to send email',
		);
	}

	/**
	 * Config fields for admin. Endpoint from constants (LLA_MFA_API_BASE_URL, LLA_MFA_API_PATH).
	 *
	 * @return array
	 */
	public function get_config_fields() {
		return array();
	}

	/**
	 * Build request options (base_url from LLA_MFA_API_BASE_URL + LLA_MFA_API_PATH).
	 *
	 * @return array
	 */
	private function get_request_options() {
		$base = defined( 'LLA_MFA_API_BASE_URL' ) ? rtrim( (string) LLA_MFA_API_BASE_URL, '/' ) : 'https://api.limitloginattempts.com';
		$path = defined( 'LLA_MFA_API_PATH' ) ? (string) LLA_MFA_API_PATH : '/mfa';
		if ( $path !== '' && substr( $path, 0, 1 ) !== '/' ) {
			$path = '/' . $path;
		}
		$base_url = $path !== '' ? $base . $path : $base;
		return array( 'base_url' => $base_url );
	}
}
